server:
  port: 8014
spring:
  application:
    name: api-order-submit
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    rabbitmq:
      host: 47.96.11.185
      port: 5672
      virtual-host: host1
      username: zhangsan
      password: admin123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://Luffy:123456@localhost:8761/eureka
feign:
  hystrix:
    enabled: true
#hystrix:
#  metrics:
#    enabled: true

