server:
  port: 9068
spring:
  application:
    name: order-close

eureka:
  client:
    service-url:
      defaultZone: http://Luffy:123456@localhost:8761/eureka
feign:
  hystrix:
    enabled: true



