server:
  port: 9067
spring:
  application:
    name: order-status-update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fmmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
eureka:
  client:
    service-url:
      defaultZone: http://Luffy:123456@localhost:8761/eureka
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.wangc.fmmall.entity


