#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/fmmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: root
#  redis:
#    port: 6379
#    host: 127.0.0.1
#    database: 0
#mybatis:
#  mapper-locations:  classpath:mappers/*Mapper.xml
#  type-aliases-package: com.wangc.fmmall.entity
#logging:
#  level:
#    io.swagger.models.parameters.AbstractSerializableParameter: error
#redisson:
#  addr:
#    singleAddr:
#      host: redis://127.0.0.1:6379
#      database: 0
