server:
  port: 9044
spring:
  application:
    name: order-add
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fmmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
eureka:
  client:
    service-url:
      defaultZone: http://Luffy:123456@localhost:8761/eureka
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.wangc.fmmall.entity
